services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: host.docker.internal
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: bateponto
      DB_PORT: 3306